using Doc.Pulse.Core.Entities.ApiInformationAggregate;
using Doc.Pulse.Core.Entities.ValueObjects;

namespace Doc.Pulse.Api;

public static partial class SeedData
{
    public static List<ApiInformation> ApiInformation = 
    [
        Core.Entities.ApiInformationAggregate.ApiInformation.New(
            "Pulse Api",
            "Generated by Clean Architecture Template",
            new AgencyContact("---", "Office of Technology Services", "DOC AppDM", "Attn. AppDmDOC Developers", "...", ""),
            new AgencyContact("APPDM", "...", "...", "...", "...", ""),
            EffectiveDate.New(DateTimeOffset.Now)
            )
    ];
}
